#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MiniClient.Resource", IsApplication=true)]

namespace MiniClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Matrix.Resource.String.ApplicationName = global::MiniClient.Resource.String.ApplicationName;
			global::Messaging.Resource.String.ApplicationName = global::MiniClient.Resource.String.ApplicationName;
			global::Messaging.Resource.String.app_name = global::MiniClient.Resource.String.app_name;
			global::Messaging.Resource.String.library_name = global::MiniClient.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int cmdConnect = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int cmdDisconnect = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int editHostname = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int editPassword = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int editUsername = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int editXmppDomain = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int fragmentContainer = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int imageItem = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int linearText = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int listContacts = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int logLinearLayout = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int logScrollView = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int txtName = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int txtStatus = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int widget28 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Contacts = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Log = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RosterListItem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int hint_domain = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hint_password = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int hint_username = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
