#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.vasundharareddy.emojicon.Resource", IsApplication=false)]

namespace com.vasundharareddy.emojicon
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int emojiconSize = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int emojiconTextLength = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int emojiconTextStart = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int horizontal_divider = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int horizontal_vertical = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int emoji_0023 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int emoji_0030 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int emoji_0031 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int emoji_0032 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int emoji_0033 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int emoji_0034 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int emoji_0035 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int emoji_0036 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int emoji_0037 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int emoji_0038 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int emoji_0039 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int emoji_00a9 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int emoji_00ae = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int emoji_1f004 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int emoji_1f0cf = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int emoji_1f170 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int emoji_1f171 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int emoji_1f17e = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int emoji_1f17f = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int emoji_1f18e = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int emoji_1f191 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int emoji_1f192 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int emoji_1f193 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int emoji_1f194 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int emoji_1f195 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int emoji_1f196 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int emoji_1f197 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int emoji_1f198 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int emoji_1f199 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int emoji_1f19a = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int emoji_1f1e8_1f1f3 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int emoji_1f1e9_1f1ea = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int emoji_1f1ea_1f1f8 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int emoji_1f1eb_1f1f7 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int emoji_1f1ec_1f1e7 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int emoji_1f1ee_1f1f9 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int emoji_1f1ef_1f1f5 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int emoji_1f1f0_1f1f7 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int emoji_1f1f7_1f1fa = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int emoji_1f1fa_1f1f8 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int emoji_1f201 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int emoji_1f202 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public static int emoji_1f21a = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public static int emoji_1f22f = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public static int emoji_1f232 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public static int emoji_1f233 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public static int emoji_1f234 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public static int emoji_1f235 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public static int emoji_1f236 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public static int emoji_1f237 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public static int emoji_1f238 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public static int emoji_1f239 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public static int emoji_1f23a = 2130837556;
			
			// aapt resource value: 0x7f020035
			public static int emoji_1f250 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public static int emoji_1f251 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public static int emoji_1f300 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public static int emoji_1f301 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public static int emoji_1f302 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public static int emoji_1f303 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public static int emoji_1f304 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public static int emoji_1f305 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public static int emoji_1f306 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public static int emoji_1f307 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public static int emoji_1f308 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public static int emoji_1f309 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public static int emoji_1f30a = 2130837569;
			
			// aapt resource value: 0x7f020042
			public static int emoji_1f30b = 2130837570;
			
			// aapt resource value: 0x7f020043
			public static int emoji_1f30c = 2130837571;
			
			// aapt resource value: 0x7f020044
			public static int emoji_1f30d = 2130837572;
			
			// aapt resource value: 0x7f020045
			public static int emoji_1f30e = 2130837573;
			
			// aapt resource value: 0x7f020046
			public static int emoji_1f30f = 2130837574;
			
			// aapt resource value: 0x7f020047
			public static int emoji_1f310 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public static int emoji_1f311 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public static int emoji_1f312 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public static int emoji_1f313 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public static int emoji_1f314 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public static int emoji_1f315 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public static int emoji_1f316 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public static int emoji_1f317 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public static int emoji_1f318 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public static int emoji_1f319 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public static int emoji_1f31a = 2130837585;
			
			// aapt resource value: 0x7f020052
			public static int emoji_1f31b = 2130837586;
			
			// aapt resource value: 0x7f020053
			public static int emoji_1f31c = 2130837587;
			
			// aapt resource value: 0x7f020054
			public static int emoji_1f31d = 2130837588;
			
			// aapt resource value: 0x7f020055
			public static int emoji_1f31e = 2130837589;
			
			// aapt resource value: 0x7f020056
			public static int emoji_1f31f = 2130837590;
			
			// aapt resource value: 0x7f020057
			public static int emoji_1f330 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public static int emoji_1f331 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public static int emoji_1f332 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public static int emoji_1f333 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public static int emoji_1f334 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public static int emoji_1f335 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public static int emoji_1f337 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public static int emoji_1f338 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public static int emoji_1f339 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public static int emoji_1f33a = 2130837600;
			
			// aapt resource value: 0x7f020061
			public static int emoji_1f33b = 2130837601;
			
			// aapt resource value: 0x7f020062
			public static int emoji_1f33c = 2130837602;
			
			// aapt resource value: 0x7f020063
			public static int emoji_1f33d = 2130837603;
			
			// aapt resource value: 0x7f020064
			public static int emoji_1f33e = 2130837604;
			
			// aapt resource value: 0x7f020065
			public static int emoji_1f33f = 2130837605;
			
			// aapt resource value: 0x7f020066
			public static int emoji_1f340 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public static int emoji_1f341 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public static int emoji_1f342 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public static int emoji_1f343 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public static int emoji_1f344 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public static int emoji_1f345 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public static int emoji_1f346 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public static int emoji_1f347 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public static int emoji_1f348 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public static int emoji_1f349 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public static int emoji_1f34a = 2130837616;
			
			// aapt resource value: 0x7f020071
			public static int emoji_1f34b = 2130837617;
			
			// aapt resource value: 0x7f020072
			public static int emoji_1f34c = 2130837618;
			
			// aapt resource value: 0x7f020073
			public static int emoji_1f34d = 2130837619;
			
			// aapt resource value: 0x7f020074
			public static int emoji_1f34e = 2130837620;
			
			// aapt resource value: 0x7f020075
			public static int emoji_1f34f = 2130837621;
			
			// aapt resource value: 0x7f020076
			public static int emoji_1f350 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public static int emoji_1f351 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public static int emoji_1f352 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public static int emoji_1f353 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public static int emoji_1f354 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public static int emoji_1f355 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public static int emoji_1f356 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public static int emoji_1f357 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public static int emoji_1f358 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public static int emoji_1f359 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public static int emoji_1f35a = 2130837632;
			
			// aapt resource value: 0x7f020081
			public static int emoji_1f35b = 2130837633;
			
			// aapt resource value: 0x7f020082
			public static int emoji_1f35c = 2130837634;
			
			// aapt resource value: 0x7f020083
			public static int emoji_1f35d = 2130837635;
			
			// aapt resource value: 0x7f020084
			public static int emoji_1f35e = 2130837636;
			
			// aapt resource value: 0x7f020085
			public static int emoji_1f35f = 2130837637;
			
			// aapt resource value: 0x7f020086
			public static int emoji_1f360 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public static int emoji_1f361 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public static int emoji_1f362 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public static int emoji_1f363 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public static int emoji_1f364 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public static int emoji_1f365 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public static int emoji_1f366 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public static int emoji_1f367 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public static int emoji_1f368 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public static int emoji_1f369 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public static int emoji_1f36a = 2130837648;
			
			// aapt resource value: 0x7f020091
			public static int emoji_1f36b = 2130837649;
			
			// aapt resource value: 0x7f020092
			public static int emoji_1f36c = 2130837650;
			
			// aapt resource value: 0x7f020093
			public static int emoji_1f36d = 2130837651;
			
			// aapt resource value: 0x7f020094
			public static int emoji_1f36e = 2130837652;
			
			// aapt resource value: 0x7f020095
			public static int emoji_1f36f = 2130837653;
			
			// aapt resource value: 0x7f020096
			public static int emoji_1f370 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public static int emoji_1f371 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public static int emoji_1f372 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public static int emoji_1f373 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public static int emoji_1f374 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public static int emoji_1f375 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public static int emoji_1f376 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public static int emoji_1f377 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public static int emoji_1f378 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public static int emoji_1f379 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public static int emoji_1f37a = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public static int emoji_1f37b = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public static int emoji_1f37c = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public static int emoji_1f380 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public static int emoji_1f381 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public static int emoji_1f382 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public static int emoji_1f383 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public static int emoji_1f384 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public static int emoji_1f385 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public static int emoji_1f386 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public static int emoji_1f387 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public static int emoji_1f388 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public static int emoji_1f389 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public static int emoji_1f38a = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public static int emoji_1f38b = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public static int emoji_1f38c = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public static int emoji_1f38d = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public static int emoji_1f38e = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public static int emoji_1f38f = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public static int emoji_1f390 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public static int emoji_1f391 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public static int emoji_1f392 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public static int emoji_1f393 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public static int emoji_1f3a0 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public static int emoji_1f3a1 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public static int emoji_1f3a2 = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public static int emoji_1f3a3 = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public static int emoji_1f3a4 = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public static int emoji_1f3a5 = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public static int emoji_1f3a6 = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public static int emoji_1f3a7 = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public static int emoji_1f3a8 = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public static int emoji_1f3a9 = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public static int emoji_1f3aa = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public static int emoji_1f3ab = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public static int emoji_1f3ac = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public static int emoji_1f3ad = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public static int emoji_1f3ae = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public static int emoji_1f3af = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public static int emoji_1f3b0 = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public static int emoji_1f3b1 = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public static int emoji_1f3b2 = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public static int emoji_1f3b3 = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public static int emoji_1f3b4 = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public static int emoji_1f3b5 = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public static int emoji_1f3b6 = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public static int emoji_1f3b7 = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public static int emoji_1f3b8 = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public static int emoji_1f3b9 = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public static int emoji_1f3ba = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public static int emoji_1f3bb = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public static int emoji_1f3bc = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public static int emoji_1f3bd = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public static int emoji_1f3be = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public static int emoji_1f3bf = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public static int emoji_1f3c0 = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public static int emoji_1f3c1 = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public static int emoji_1f3c2 = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public static int emoji_1f3c3 = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public static int emoji_1f3c4 = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public static int emoji_1f3c6 = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public static int emoji_1f3c7 = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public static int emoji_1f3c8 = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public static int emoji_1f3c9 = 2130837727;
			
			// aapt resource value: 0x7f0200e0
			public static int emoji_1f3ca = 2130837728;
			
			// aapt resource value: 0x7f0200e1
			public static int emoji_1f3e0 = 2130837729;
			
			// aapt resource value: 0x7f0200e2
			public static int emoji_1f3e1 = 2130837730;
			
			// aapt resource value: 0x7f0200e3
			public static int emoji_1f3e2 = 2130837731;
			
			// aapt resource value: 0x7f0200e4
			public static int emoji_1f3e3 = 2130837732;
			
			// aapt resource value: 0x7f0200e5
			public static int emoji_1f3e4 = 2130837733;
			
			// aapt resource value: 0x7f0200e6
			public static int emoji_1f3e5 = 2130837734;
			
			// aapt resource value: 0x7f0200e7
			public static int emoji_1f3e6 = 2130837735;
			
			// aapt resource value: 0x7f0200e8
			public static int emoji_1f3e7 = 2130837736;
			
			// aapt resource value: 0x7f0200e9
			public static int emoji_1f3e8 = 2130837737;
			
			// aapt resource value: 0x7f0200ea
			public static int emoji_1f3e9 = 2130837738;
			
			// aapt resource value: 0x7f0200eb
			public static int emoji_1f3ea = 2130837739;
			
			// aapt resource value: 0x7f0200ec
			public static int emoji_1f3eb = 2130837740;
			
			// aapt resource value: 0x7f0200ed
			public static int emoji_1f3ec = 2130837741;
			
			// aapt resource value: 0x7f0200ee
			public static int emoji_1f3ed = 2130837742;
			
			// aapt resource value: 0x7f0200ef
			public static int emoji_1f3ee = 2130837743;
			
			// aapt resource value: 0x7f0200f0
			public static int emoji_1f3ef = 2130837744;
			
			// aapt resource value: 0x7f0200f1
			public static int emoji_1f3f0 = 2130837745;
			
			// aapt resource value: 0x7f0200f2
			public static int emoji_1f400 = 2130837746;
			
			// aapt resource value: 0x7f0200f3
			public static int emoji_1f401 = 2130837747;
			
			// aapt resource value: 0x7f0200f4
			public static int emoji_1f402 = 2130837748;
			
			// aapt resource value: 0x7f0200f5
			public static int emoji_1f403 = 2130837749;
			
			// aapt resource value: 0x7f0200f6
			public static int emoji_1f404 = 2130837750;
			
			// aapt resource value: 0x7f0200f7
			public static int emoji_1f405 = 2130837751;
			
			// aapt resource value: 0x7f0200f8
			public static int emoji_1f406 = 2130837752;
			
			// aapt resource value: 0x7f0200f9
			public static int emoji_1f407 = 2130837753;
			
			// aapt resource value: 0x7f0200fa
			public static int emoji_1f408 = 2130837754;
			
			// aapt resource value: 0x7f0200fb
			public static int emoji_1f409 = 2130837755;
			
			// aapt resource value: 0x7f0200fc
			public static int emoji_1f40a = 2130837756;
			
			// aapt resource value: 0x7f0200fd
			public static int emoji_1f40b = 2130837757;
			
			// aapt resource value: 0x7f0200fe
			public static int emoji_1f40c = 2130837758;
			
			// aapt resource value: 0x7f0200ff
			public static int emoji_1f40d = 2130837759;
			
			// aapt resource value: 0x7f020100
			public static int emoji_1f40e = 2130837760;
			
			// aapt resource value: 0x7f020101
			public static int emoji_1f40f = 2130837761;
			
			// aapt resource value: 0x7f020102
			public static int emoji_1f410 = 2130837762;
			
			// aapt resource value: 0x7f020103
			public static int emoji_1f411 = 2130837763;
			
			// aapt resource value: 0x7f020104
			public static int emoji_1f412 = 2130837764;
			
			// aapt resource value: 0x7f020105
			public static int emoji_1f413 = 2130837765;
			
			// aapt resource value: 0x7f020106
			public static int emoji_1f414 = 2130837766;
			
			// aapt resource value: 0x7f020107
			public static int emoji_1f415 = 2130837767;
			
			// aapt resource value: 0x7f020108
			public static int emoji_1f416 = 2130837768;
			
			// aapt resource value: 0x7f020109
			public static int emoji_1f417 = 2130837769;
			
			// aapt resource value: 0x7f02010a
			public static int emoji_1f418 = 2130837770;
			
			// aapt resource value: 0x7f02010b
			public static int emoji_1f419 = 2130837771;
			
			// aapt resource value: 0x7f02010c
			public static int emoji_1f41a = 2130837772;
			
			// aapt resource value: 0x7f02010d
			public static int emoji_1f41b = 2130837773;
			
			// aapt resource value: 0x7f02010e
			public static int emoji_1f41c = 2130837774;
			
			// aapt resource value: 0x7f02010f
			public static int emoji_1f41d = 2130837775;
			
			// aapt resource value: 0x7f020110
			public static int emoji_1f41e = 2130837776;
			
			// aapt resource value: 0x7f020111
			public static int emoji_1f41f = 2130837777;
			
			// aapt resource value: 0x7f020112
			public static int emoji_1f420 = 2130837778;
			
			// aapt resource value: 0x7f020113
			public static int emoji_1f421 = 2130837779;
			
			// aapt resource value: 0x7f020114
			public static int emoji_1f422 = 2130837780;
			
			// aapt resource value: 0x7f020115
			public static int emoji_1f423 = 2130837781;
			
			// aapt resource value: 0x7f020116
			public static int emoji_1f424 = 2130837782;
			
			// aapt resource value: 0x7f020117
			public static int emoji_1f425 = 2130837783;
			
			// aapt resource value: 0x7f020118
			public static int emoji_1f426 = 2130837784;
			
			// aapt resource value: 0x7f020119
			public static int emoji_1f427 = 2130837785;
			
			// aapt resource value: 0x7f02011a
			public static int emoji_1f428 = 2130837786;
			
			// aapt resource value: 0x7f02011b
			public static int emoji_1f429 = 2130837787;
			
			// aapt resource value: 0x7f02011c
			public static int emoji_1f42a = 2130837788;
			
			// aapt resource value: 0x7f02011d
			public static int emoji_1f42b = 2130837789;
			
			// aapt resource value: 0x7f02011e
			public static int emoji_1f42c = 2130837790;
			
			// aapt resource value: 0x7f02011f
			public static int emoji_1f42d = 2130837791;
			
			// aapt resource value: 0x7f020120
			public static int emoji_1f42e = 2130837792;
			
			// aapt resource value: 0x7f020121
			public static int emoji_1f42f = 2130837793;
			
			// aapt resource value: 0x7f020122
			public static int emoji_1f430 = 2130837794;
			
			// aapt resource value: 0x7f020123
			public static int emoji_1f431 = 2130837795;
			
			// aapt resource value: 0x7f020124
			public static int emoji_1f432 = 2130837796;
			
			// aapt resource value: 0x7f020125
			public static int emoji_1f433 = 2130837797;
			
			// aapt resource value: 0x7f020126
			public static int emoji_1f434 = 2130837798;
			
			// aapt resource value: 0x7f020127
			public static int emoji_1f435 = 2130837799;
			
			// aapt resource value: 0x7f020128
			public static int emoji_1f436 = 2130837800;
			
			// aapt resource value: 0x7f020129
			public static int emoji_1f437 = 2130837801;
			
			// aapt resource value: 0x7f02012a
			public static int emoji_1f438 = 2130837802;
			
			// aapt resource value: 0x7f02012b
			public static int emoji_1f439 = 2130837803;
			
			// aapt resource value: 0x7f02012c
			public static int emoji_1f43a = 2130837804;
			
			// aapt resource value: 0x7f02012d
			public static int emoji_1f43b = 2130837805;
			
			// aapt resource value: 0x7f02012e
			public static int emoji_1f43c = 2130837806;
			
			// aapt resource value: 0x7f02012f
			public static int emoji_1f43d = 2130837807;
			
			// aapt resource value: 0x7f020130
			public static int emoji_1f43e = 2130837808;
			
			// aapt resource value: 0x7f020131
			public static int emoji_1f440 = 2130837809;
			
			// aapt resource value: 0x7f020132
			public static int emoji_1f442 = 2130837810;
			
			// aapt resource value: 0x7f020133
			public static int emoji_1f443 = 2130837811;
			
			// aapt resource value: 0x7f020134
			public static int emoji_1f444 = 2130837812;
			
			// aapt resource value: 0x7f020135
			public static int emoji_1f445 = 2130837813;
			
			// aapt resource value: 0x7f020136
			public static int emoji_1f446 = 2130837814;
			
			// aapt resource value: 0x7f020137
			public static int emoji_1f447 = 2130837815;
			
			// aapt resource value: 0x7f020138
			public static int emoji_1f448 = 2130837816;
			
			// aapt resource value: 0x7f020139
			public static int emoji_1f449 = 2130837817;
			
			// aapt resource value: 0x7f02013a
			public static int emoji_1f44a = 2130837818;
			
			// aapt resource value: 0x7f02013b
			public static int emoji_1f44b = 2130837819;
			
			// aapt resource value: 0x7f02013c
			public static int emoji_1f44c = 2130837820;
			
			// aapt resource value: 0x7f02013d
			public static int emoji_1f44d = 2130837821;
			
			// aapt resource value: 0x7f02013e
			public static int emoji_1f44e = 2130837822;
			
			// aapt resource value: 0x7f02013f
			public static int emoji_1f44f = 2130837823;
			
			// aapt resource value: 0x7f020140
			public static int emoji_1f450 = 2130837824;
			
			// aapt resource value: 0x7f020141
			public static int emoji_1f451 = 2130837825;
			
			// aapt resource value: 0x7f020142
			public static int emoji_1f452 = 2130837826;
			
			// aapt resource value: 0x7f020143
			public static int emoji_1f453 = 2130837827;
			
			// aapt resource value: 0x7f020144
			public static int emoji_1f454 = 2130837828;
			
			// aapt resource value: 0x7f020145
			public static int emoji_1f455 = 2130837829;
			
			// aapt resource value: 0x7f020146
			public static int emoji_1f456 = 2130837830;
			
			// aapt resource value: 0x7f020147
			public static int emoji_1f457 = 2130837831;
			
			// aapt resource value: 0x7f020148
			public static int emoji_1f458 = 2130837832;
			
			// aapt resource value: 0x7f020149
			public static int emoji_1f459 = 2130837833;
			
			// aapt resource value: 0x7f02014a
			public static int emoji_1f45a = 2130837834;
			
			// aapt resource value: 0x7f02014b
			public static int emoji_1f45b = 2130837835;
			
			// aapt resource value: 0x7f02014c
			public static int emoji_1f45c = 2130837836;
			
			// aapt resource value: 0x7f02014d
			public static int emoji_1f45d = 2130837837;
			
			// aapt resource value: 0x7f02014e
			public static int emoji_1f45e = 2130837838;
			
			// aapt resource value: 0x7f02014f
			public static int emoji_1f45f = 2130837839;
			
			// aapt resource value: 0x7f020150
			public static int emoji_1f460 = 2130837840;
			
			// aapt resource value: 0x7f020151
			public static int emoji_1f461 = 2130837841;
			
			// aapt resource value: 0x7f020152
			public static int emoji_1f462 = 2130837842;
			
			// aapt resource value: 0x7f020153
			public static int emoji_1f463 = 2130837843;
			
			// aapt resource value: 0x7f020154
			public static int emoji_1f464 = 2130837844;
			
			// aapt resource value: 0x7f020155
			public static int emoji_1f465 = 2130837845;
			
			// aapt resource value: 0x7f020156
			public static int emoji_1f466 = 2130837846;
			
			// aapt resource value: 0x7f020157
			public static int emoji_1f467 = 2130837847;
			
			// aapt resource value: 0x7f020158
			public static int emoji_1f468 = 2130837848;
			
			// aapt resource value: 0x7f020159
			public static int emoji_1f469 = 2130837849;
			
			// aapt resource value: 0x7f02015a
			public static int emoji_1f46a = 2130837850;
			
			// aapt resource value: 0x7f02015b
			public static int emoji_1f46b = 2130837851;
			
			// aapt resource value: 0x7f02015c
			public static int emoji_1f46c = 2130837852;
			
			// aapt resource value: 0x7f02015d
			public static int emoji_1f46d = 2130837853;
			
			// aapt resource value: 0x7f02015e
			public static int emoji_1f46e = 2130837854;
			
			// aapt resource value: 0x7f02015f
			public static int emoji_1f46f = 2130837855;
			
			// aapt resource value: 0x7f020160
			public static int emoji_1f470 = 2130837856;
			
			// aapt resource value: 0x7f020161
			public static int emoji_1f471 = 2130837857;
			
			// aapt resource value: 0x7f020162
			public static int emoji_1f472 = 2130837858;
			
			// aapt resource value: 0x7f020163
			public static int emoji_1f473 = 2130837859;
			
			// aapt resource value: 0x7f020164
			public static int emoji_1f474 = 2130837860;
			
			// aapt resource value: 0x7f020165
			public static int emoji_1f475 = 2130837861;
			
			// aapt resource value: 0x7f020166
			public static int emoji_1f476 = 2130837862;
			
			// aapt resource value: 0x7f020167
			public static int emoji_1f477 = 2130837863;
			
			// aapt resource value: 0x7f020168
			public static int emoji_1f478 = 2130837864;
			
			// aapt resource value: 0x7f020169
			public static int emoji_1f479 = 2130837865;
			
			// aapt resource value: 0x7f02016a
			public static int emoji_1f47a = 2130837866;
			
			// aapt resource value: 0x7f02016b
			public static int emoji_1f47b = 2130837867;
			
			// aapt resource value: 0x7f02016c
			public static int emoji_1f47c = 2130837868;
			
			// aapt resource value: 0x7f02016d
			public static int emoji_1f47d = 2130837869;
			
			// aapt resource value: 0x7f02016e
			public static int emoji_1f47e = 2130837870;
			
			// aapt resource value: 0x7f02016f
			public static int emoji_1f47f = 2130837871;
			
			// aapt resource value: 0x7f020170
			public static int emoji_1f480 = 2130837872;
			
			// aapt resource value: 0x7f020171
			public static int emoji_1f481 = 2130837873;
			
			// aapt resource value: 0x7f020172
			public static int emoji_1f482 = 2130837874;
			
			// aapt resource value: 0x7f020173
			public static int emoji_1f483 = 2130837875;
			
			// aapt resource value: 0x7f020174
			public static int emoji_1f484 = 2130837876;
			
			// aapt resource value: 0x7f020175
			public static int emoji_1f485 = 2130837877;
			
			// aapt resource value: 0x7f020176
			public static int emoji_1f486 = 2130837878;
			
			// aapt resource value: 0x7f020177
			public static int emoji_1f487 = 2130837879;
			
			// aapt resource value: 0x7f020178
			public static int emoji_1f488 = 2130837880;
			
			// aapt resource value: 0x7f020179
			public static int emoji_1f489 = 2130837881;
			
			// aapt resource value: 0x7f02017a
			public static int emoji_1f48a = 2130837882;
			
			// aapt resource value: 0x7f02017b
			public static int emoji_1f48b = 2130837883;
			
			// aapt resource value: 0x7f02017c
			public static int emoji_1f48c = 2130837884;
			
			// aapt resource value: 0x7f02017d
			public static int emoji_1f48d = 2130837885;
			
			// aapt resource value: 0x7f02017e
			public static int emoji_1f48e = 2130837886;
			
			// aapt resource value: 0x7f02017f
			public static int emoji_1f48f = 2130837887;
			
			// aapt resource value: 0x7f020180
			public static int emoji_1f490 = 2130837888;
			
			// aapt resource value: 0x7f020181
			public static int emoji_1f491 = 2130837889;
			
			// aapt resource value: 0x7f020182
			public static int emoji_1f492 = 2130837890;
			
			// aapt resource value: 0x7f020183
			public static int emoji_1f493 = 2130837891;
			
			// aapt resource value: 0x7f020184
			public static int emoji_1f494 = 2130837892;
			
			// aapt resource value: 0x7f020185
			public static int emoji_1f495 = 2130837893;
			
			// aapt resource value: 0x7f020186
			public static int emoji_1f496 = 2130837894;
			
			// aapt resource value: 0x7f020187
			public static int emoji_1f497 = 2130837895;
			
			// aapt resource value: 0x7f020188
			public static int emoji_1f498 = 2130837896;
			
			// aapt resource value: 0x7f020189
			public static int emoji_1f499 = 2130837897;
			
			// aapt resource value: 0x7f02018a
			public static int emoji_1f49a = 2130837898;
			
			// aapt resource value: 0x7f02018b
			public static int emoji_1f49b = 2130837899;
			
			// aapt resource value: 0x7f02018c
			public static int emoji_1f49c = 2130837900;
			
			// aapt resource value: 0x7f02018d
			public static int emoji_1f49d = 2130837901;
			
			// aapt resource value: 0x7f02018e
			public static int emoji_1f49e = 2130837902;
			
			// aapt resource value: 0x7f02018f
			public static int emoji_1f49f = 2130837903;
			
			// aapt resource value: 0x7f020190
			public static int emoji_1f4a0 = 2130837904;
			
			// aapt resource value: 0x7f020191
			public static int emoji_1f4a1 = 2130837905;
			
			// aapt resource value: 0x7f020192
			public static int emoji_1f4a2 = 2130837906;
			
			// aapt resource value: 0x7f020193
			public static int emoji_1f4a3 = 2130837907;
			
			// aapt resource value: 0x7f020194
			public static int emoji_1f4a4 = 2130837908;
			
			// aapt resource value: 0x7f020195
			public static int emoji_1f4a5 = 2130837909;
			
			// aapt resource value: 0x7f020196
			public static int emoji_1f4a6 = 2130837910;
			
			// aapt resource value: 0x7f020197
			public static int emoji_1f4a7 = 2130837911;
			
			// aapt resource value: 0x7f020198
			public static int emoji_1f4a8 = 2130837912;
			
			// aapt resource value: 0x7f020199
			public static int emoji_1f4a9 = 2130837913;
			
			// aapt resource value: 0x7f02019a
			public static int emoji_1f4aa = 2130837914;
			
			// aapt resource value: 0x7f02019b
			public static int emoji_1f4ab = 2130837915;
			
			// aapt resource value: 0x7f02019c
			public static int emoji_1f4ac = 2130837916;
			
			// aapt resource value: 0x7f02019d
			public static int emoji_1f4ad = 2130837917;
			
			// aapt resource value: 0x7f02019e
			public static int emoji_1f4ae = 2130837918;
			
			// aapt resource value: 0x7f02019f
			public static int emoji_1f4af = 2130837919;
			
			// aapt resource value: 0x7f0201a0
			public static int emoji_1f4b0 = 2130837920;
			
			// aapt resource value: 0x7f0201a1
			public static int emoji_1f4b1 = 2130837921;
			
			// aapt resource value: 0x7f0201a2
			public static int emoji_1f4b2 = 2130837922;
			
			// aapt resource value: 0x7f0201a3
			public static int emoji_1f4b3 = 2130837923;
			
			// aapt resource value: 0x7f0201a4
			public static int emoji_1f4b4 = 2130837924;
			
			// aapt resource value: 0x7f0201a5
			public static int emoji_1f4b5 = 2130837925;
			
			// aapt resource value: 0x7f0201a6
			public static int emoji_1f4b6 = 2130837926;
			
			// aapt resource value: 0x7f0201a7
			public static int emoji_1f4b7 = 2130837927;
			
			// aapt resource value: 0x7f0201a8
			public static int emoji_1f4b8 = 2130837928;
			
			// aapt resource value: 0x7f0201a9
			public static int emoji_1f4b9 = 2130837929;
			
			// aapt resource value: 0x7f0201aa
			public static int emoji_1f4ba = 2130837930;
			
			// aapt resource value: 0x7f0201ab
			public static int emoji_1f4bb = 2130837931;
			
			// aapt resource value: 0x7f0201ac
			public static int emoji_1f4bc = 2130837932;
			
			// aapt resource value: 0x7f0201ad
			public static int emoji_1f4bd = 2130837933;
			
			// aapt resource value: 0x7f0201ae
			public static int emoji_1f4be = 2130837934;
			
			// aapt resource value: 0x7f0201af
			public static int emoji_1f4bf = 2130837935;
			
			// aapt resource value: 0x7f0201b0
			public static int emoji_1f4c0 = 2130837936;
			
			// aapt resource value: 0x7f0201b1
			public static int emoji_1f4c1 = 2130837937;
			
			// aapt resource value: 0x7f0201b2
			public static int emoji_1f4c2 = 2130837938;
			
			// aapt resource value: 0x7f0201b3
			public static int emoji_1f4c3 = 2130837939;
			
			// aapt resource value: 0x7f0201b4
			public static int emoji_1f4c4 = 2130837940;
			
			// aapt resource value: 0x7f0201b5
			public static int emoji_1f4c5 = 2130837941;
			
			// aapt resource value: 0x7f0201b6
			public static int emoji_1f4c6 = 2130837942;
			
			// aapt resource value: 0x7f0201b7
			public static int emoji_1f4c7 = 2130837943;
			
			// aapt resource value: 0x7f0201b8
			public static int emoji_1f4c8 = 2130837944;
			
			// aapt resource value: 0x7f0201b9
			public static int emoji_1f4c9 = 2130837945;
			
			// aapt resource value: 0x7f0201ba
			public static int emoji_1f4ca = 2130837946;
			
			// aapt resource value: 0x7f0201bb
			public static int emoji_1f4cb = 2130837947;
			
			// aapt resource value: 0x7f0201bc
			public static int emoji_1f4cc = 2130837948;
			
			// aapt resource value: 0x7f0201bd
			public static int emoji_1f4cd = 2130837949;
			
			// aapt resource value: 0x7f0201be
			public static int emoji_1f4ce = 2130837950;
			
			// aapt resource value: 0x7f0201bf
			public static int emoji_1f4cf = 2130837951;
			
			// aapt resource value: 0x7f0201c0
			public static int emoji_1f4d0 = 2130837952;
			
			// aapt resource value: 0x7f0201c1
			public static int emoji_1f4d1 = 2130837953;
			
			// aapt resource value: 0x7f0201c2
			public static int emoji_1f4d2 = 2130837954;
			
			// aapt resource value: 0x7f0201c3
			public static int emoji_1f4d3 = 2130837955;
			
			// aapt resource value: 0x7f0201c4
			public static int emoji_1f4d4 = 2130837956;
			
			// aapt resource value: 0x7f0201c5
			public static int emoji_1f4d5 = 2130837957;
			
			// aapt resource value: 0x7f0201c6
			public static int emoji_1f4d6 = 2130837958;
			
			// aapt resource value: 0x7f0201c7
			public static int emoji_1f4d7 = 2130837959;
			
			// aapt resource value: 0x7f0201c8
			public static int emoji_1f4d8 = 2130837960;
			
			// aapt resource value: 0x7f0201c9
			public static int emoji_1f4d9 = 2130837961;
			
			// aapt resource value: 0x7f0201ca
			public static int emoji_1f4da = 2130837962;
			
			// aapt resource value: 0x7f0201cb
			public static int emoji_1f4db = 2130837963;
			
			// aapt resource value: 0x7f0201cc
			public static int emoji_1f4dc = 2130837964;
			
			// aapt resource value: 0x7f0201cd
			public static int emoji_1f4dd = 2130837965;
			
			// aapt resource value: 0x7f0201ce
			public static int emoji_1f4de = 2130837966;
			
			// aapt resource value: 0x7f0201cf
			public static int emoji_1f4df = 2130837967;
			
			// aapt resource value: 0x7f0201d0
			public static int emoji_1f4e0 = 2130837968;
			
			// aapt resource value: 0x7f0201d1
			public static int emoji_1f4e1 = 2130837969;
			
			// aapt resource value: 0x7f0201d2
			public static int emoji_1f4e2 = 2130837970;
			
			// aapt resource value: 0x7f0201d3
			public static int emoji_1f4e3 = 2130837971;
			
			// aapt resource value: 0x7f0201d4
			public static int emoji_1f4e4 = 2130837972;
			
			// aapt resource value: 0x7f0201d5
			public static int emoji_1f4e5 = 2130837973;
			
			// aapt resource value: 0x7f0201d6
			public static int emoji_1f4e6 = 2130837974;
			
			// aapt resource value: 0x7f0201d7
			public static int emoji_1f4e7 = 2130837975;
			
			// aapt resource value: 0x7f0201d8
			public static int emoji_1f4e8 = 2130837976;
			
			// aapt resource value: 0x7f0201d9
			public static int emoji_1f4e9 = 2130837977;
			
			// aapt resource value: 0x7f0201da
			public static int emoji_1f4ea = 2130837978;
			
			// aapt resource value: 0x7f0201db
			public static int emoji_1f4eb = 2130837979;
			
			// aapt resource value: 0x7f0201dc
			public static int emoji_1f4ec = 2130837980;
			
			// aapt resource value: 0x7f0201dd
			public static int emoji_1f4ed = 2130837981;
			
			// aapt resource value: 0x7f0201de
			public static int emoji_1f4ee = 2130837982;
			
			// aapt resource value: 0x7f0201df
			public static int emoji_1f4ef = 2130837983;
			
			// aapt resource value: 0x7f0201e0
			public static int emoji_1f4f0 = 2130837984;
			
			// aapt resource value: 0x7f0201e1
			public static int emoji_1f4f1 = 2130837985;
			
			// aapt resource value: 0x7f0201e2
			public static int emoji_1f4f2 = 2130837986;
			
			// aapt resource value: 0x7f0201e3
			public static int emoji_1f4f3 = 2130837987;
			
			// aapt resource value: 0x7f0201e4
			public static int emoji_1f4f4 = 2130837988;
			
			// aapt resource value: 0x7f0201e5
			public static int emoji_1f4f5 = 2130837989;
			
			// aapt resource value: 0x7f0201e6
			public static int emoji_1f4f6 = 2130837990;
			
			// aapt resource value: 0x7f0201e7
			public static int emoji_1f4f7 = 2130837991;
			
			// aapt resource value: 0x7f0201e8
			public static int emoji_1f4f9 = 2130837992;
			
			// aapt resource value: 0x7f0201e9
			public static int emoji_1f4fa = 2130837993;
			
			// aapt resource value: 0x7f0201ea
			public static int emoji_1f4fb = 2130837994;
			
			// aapt resource value: 0x7f0201eb
			public static int emoji_1f4fc = 2130837995;
			
			// aapt resource value: 0x7f0201ec
			public static int emoji_1f500 = 2130837996;
			
			// aapt resource value: 0x7f0201ed
			public static int emoji_1f501 = 2130837997;
			
			// aapt resource value: 0x7f0201ee
			public static int emoji_1f502 = 2130837998;
			
			// aapt resource value: 0x7f0201ef
			public static int emoji_1f503 = 2130837999;
			
			// aapt resource value: 0x7f0201f0
			public static int emoji_1f504 = 2130838000;
			
			// aapt resource value: 0x7f0201f1
			public static int emoji_1f505 = 2130838001;
			
			// aapt resource value: 0x7f0201f2
			public static int emoji_1f506 = 2130838002;
			
			// aapt resource value: 0x7f0201f3
			public static int emoji_1f507 = 2130838003;
			
			// aapt resource value: 0x7f0201f4
			public static int emoji_1f508 = 2130838004;
			
			// aapt resource value: 0x7f0201f5
			public static int emoji_1f509 = 2130838005;
			
			// aapt resource value: 0x7f0201f6
			public static int emoji_1f50a = 2130838006;
			
			// aapt resource value: 0x7f0201f7
			public static int emoji_1f50b = 2130838007;
			
			// aapt resource value: 0x7f0201f8
			public static int emoji_1f50c = 2130838008;
			
			// aapt resource value: 0x7f0201f9
			public static int emoji_1f50d = 2130838009;
			
			// aapt resource value: 0x7f0201fa
			public static int emoji_1f50e = 2130838010;
			
			// aapt resource value: 0x7f0201fb
			public static int emoji_1f50f = 2130838011;
			
			// aapt resource value: 0x7f0201fc
			public static int emoji_1f510 = 2130838012;
			
			// aapt resource value: 0x7f0201fd
			public static int emoji_1f511 = 2130838013;
			
			// aapt resource value: 0x7f0201fe
			public static int emoji_1f512 = 2130838014;
			
			// aapt resource value: 0x7f0201ff
			public static int emoji_1f513 = 2130838015;
			
			// aapt resource value: 0x7f020200
			public static int emoji_1f514 = 2130838016;
			
			// aapt resource value: 0x7f020201
			public static int emoji_1f515 = 2130838017;
			
			// aapt resource value: 0x7f020202
			public static int emoji_1f516 = 2130838018;
			
			// aapt resource value: 0x7f020203
			public static int emoji_1f517 = 2130838019;
			
			// aapt resource value: 0x7f020204
			public static int emoji_1f518 = 2130838020;
			
			// aapt resource value: 0x7f020205
			public static int emoji_1f519 = 2130838021;
			
			// aapt resource value: 0x7f020206
			public static int emoji_1f51a = 2130838022;
			
			// aapt resource value: 0x7f020207
			public static int emoji_1f51b = 2130838023;
			
			// aapt resource value: 0x7f020208
			public static int emoji_1f51c = 2130838024;
			
			// aapt resource value: 0x7f020209
			public static int emoji_1f51d = 2130838025;
			
			// aapt resource value: 0x7f02020a
			public static int emoji_1f51e = 2130838026;
			
			// aapt resource value: 0x7f02020b
			public static int emoji_1f51f = 2130838027;
			
			// aapt resource value: 0x7f02020c
			public static int emoji_1f520 = 2130838028;
			
			// aapt resource value: 0x7f02020d
			public static int emoji_1f521 = 2130838029;
			
			// aapt resource value: 0x7f02020e
			public static int emoji_1f522 = 2130838030;
			
			// aapt resource value: 0x7f02020f
			public static int emoji_1f523 = 2130838031;
			
			// aapt resource value: 0x7f020210
			public static int emoji_1f524 = 2130838032;
			
			// aapt resource value: 0x7f020211
			public static int emoji_1f525 = 2130838033;
			
			// aapt resource value: 0x7f020212
			public static int emoji_1f526 = 2130838034;
			
			// aapt resource value: 0x7f020213
			public static int emoji_1f527 = 2130838035;
			
			// aapt resource value: 0x7f020214
			public static int emoji_1f528 = 2130838036;
			
			// aapt resource value: 0x7f020215
			public static int emoji_1f529 = 2130838037;
			
			// aapt resource value: 0x7f020216
			public static int emoji_1f52a = 2130838038;
			
			// aapt resource value: 0x7f020217
			public static int emoji_1f52b = 2130838039;
			
			// aapt resource value: 0x7f020218
			public static int emoji_1f52c = 2130838040;
			
			// aapt resource value: 0x7f020219
			public static int emoji_1f52d = 2130838041;
			
			// aapt resource value: 0x7f02021a
			public static int emoji_1f52e = 2130838042;
			
			// aapt resource value: 0x7f02021b
			public static int emoji_1f52f = 2130838043;
			
			// aapt resource value: 0x7f02021c
			public static int emoji_1f530 = 2130838044;
			
			// aapt resource value: 0x7f02021d
			public static int emoji_1f531 = 2130838045;
			
			// aapt resource value: 0x7f02021e
			public static int emoji_1f532 = 2130838046;
			
			// aapt resource value: 0x7f02021f
			public static int emoji_1f533 = 2130838047;
			
			// aapt resource value: 0x7f020220
			public static int emoji_1f534 = 2130838048;
			
			// aapt resource value: 0x7f020221
			public static int emoji_1f535 = 2130838049;
			
			// aapt resource value: 0x7f020222
			public static int emoji_1f536 = 2130838050;
			
			// aapt resource value: 0x7f020223
			public static int emoji_1f537 = 2130838051;
			
			// aapt resource value: 0x7f020224
			public static int emoji_1f538 = 2130838052;
			
			// aapt resource value: 0x7f020225
			public static int emoji_1f539 = 2130838053;
			
			// aapt resource value: 0x7f020226
			public static int emoji_1f53a = 2130838054;
			
			// aapt resource value: 0x7f020227
			public static int emoji_1f53b = 2130838055;
			
			// aapt resource value: 0x7f020228
			public static int emoji_1f53c = 2130838056;
			
			// aapt resource value: 0x7f020229
			public static int emoji_1f53d = 2130838057;
			
			// aapt resource value: 0x7f02022a
			public static int emoji_1f550 = 2130838058;
			
			// aapt resource value: 0x7f02022b
			public static int emoji_1f551 = 2130838059;
			
			// aapt resource value: 0x7f02022c
			public static int emoji_1f552 = 2130838060;
			
			// aapt resource value: 0x7f02022d
			public static int emoji_1f553 = 2130838061;
			
			// aapt resource value: 0x7f02022e
			public static int emoji_1f554 = 2130838062;
			
			// aapt resource value: 0x7f02022f
			public static int emoji_1f555 = 2130838063;
			
			// aapt resource value: 0x7f020230
			public static int emoji_1f556 = 2130838064;
			
			// aapt resource value: 0x7f020231
			public static int emoji_1f557 = 2130838065;
			
			// aapt resource value: 0x7f020232
			public static int emoji_1f558 = 2130838066;
			
			// aapt resource value: 0x7f020233
			public static int emoji_1f559 = 2130838067;
			
			// aapt resource value: 0x7f020234
			public static int emoji_1f55a = 2130838068;
			
			// aapt resource value: 0x7f020235
			public static int emoji_1f55b = 2130838069;
			
			// aapt resource value: 0x7f020236
			public static int emoji_1f55c = 2130838070;
			
			// aapt resource value: 0x7f020237
			public static int emoji_1f55d = 2130838071;
			
			// aapt resource value: 0x7f020238
			public static int emoji_1f55e = 2130838072;
			
			// aapt resource value: 0x7f020239
			public static int emoji_1f55f = 2130838073;
			
			// aapt resource value: 0x7f02023a
			public static int emoji_1f560 = 2130838074;
			
			// aapt resource value: 0x7f02023b
			public static int emoji_1f561 = 2130838075;
			
			// aapt resource value: 0x7f02023c
			public static int emoji_1f562 = 2130838076;
			
			// aapt resource value: 0x7f02023d
			public static int emoji_1f563 = 2130838077;
			
			// aapt resource value: 0x7f02023e
			public static int emoji_1f564 = 2130838078;
			
			// aapt resource value: 0x7f02023f
			public static int emoji_1f565 = 2130838079;
			
			// aapt resource value: 0x7f020240
			public static int emoji_1f566 = 2130838080;
			
			// aapt resource value: 0x7f020241
			public static int emoji_1f567 = 2130838081;
			
			// aapt resource value: 0x7f020242
			public static int emoji_1f5fb = 2130838082;
			
			// aapt resource value: 0x7f020243
			public static int emoji_1f5fc = 2130838083;
			
			// aapt resource value: 0x7f020244
			public static int emoji_1f5fd = 2130838084;
			
			// aapt resource value: 0x7f020245
			public static int emoji_1f5fe = 2130838085;
			
			// aapt resource value: 0x7f020246
			public static int emoji_1f5ff = 2130838086;
			
			// aapt resource value: 0x7f020247
			public static int emoji_1f600 = 2130838087;
			
			// aapt resource value: 0x7f020248
			public static int emoji_1f601 = 2130838088;
			
			// aapt resource value: 0x7f020249
			public static int emoji_1f602 = 2130838089;
			
			// aapt resource value: 0x7f02024a
			public static int emoji_1f603 = 2130838090;
			
			// aapt resource value: 0x7f02024b
			public static int emoji_1f604 = 2130838091;
			
			// aapt resource value: 0x7f02024c
			public static int emoji_1f605 = 2130838092;
			
			// aapt resource value: 0x7f02024d
			public static int emoji_1f606 = 2130838093;
			
			// aapt resource value: 0x7f02024e
			public static int emoji_1f607 = 2130838094;
			
			// aapt resource value: 0x7f02024f
			public static int emoji_1f608 = 2130838095;
			
			// aapt resource value: 0x7f020250
			public static int emoji_1f609 = 2130838096;
			
			// aapt resource value: 0x7f020251
			public static int emoji_1f60a = 2130838097;
			
			// aapt resource value: 0x7f020252
			public static int emoji_1f60b = 2130838098;
			
			// aapt resource value: 0x7f020253
			public static int emoji_1f60c = 2130838099;
			
			// aapt resource value: 0x7f020254
			public static int emoji_1f60d = 2130838100;
			
			// aapt resource value: 0x7f020255
			public static int emoji_1f60e = 2130838101;
			
			// aapt resource value: 0x7f020256
			public static int emoji_1f60f = 2130838102;
			
			// aapt resource value: 0x7f020257
			public static int emoji_1f610 = 2130838103;
			
			// aapt resource value: 0x7f020258
			public static int emoji_1f611 = 2130838104;
			
			// aapt resource value: 0x7f020259
			public static int emoji_1f612 = 2130838105;
			
			// aapt resource value: 0x7f02025a
			public static int emoji_1f613 = 2130838106;
			
			// aapt resource value: 0x7f02025b
			public static int emoji_1f614 = 2130838107;
			
			// aapt resource value: 0x7f02025c
			public static int emoji_1f615 = 2130838108;
			
			// aapt resource value: 0x7f02025d
			public static int emoji_1f616 = 2130838109;
			
			// aapt resource value: 0x7f02025e
			public static int emoji_1f617 = 2130838110;
			
			// aapt resource value: 0x7f02025f
			public static int emoji_1f618 = 2130838111;
			
			// aapt resource value: 0x7f020260
			public static int emoji_1f619 = 2130838112;
			
			// aapt resource value: 0x7f020261
			public static int emoji_1f61a = 2130838113;
			
			// aapt resource value: 0x7f020262
			public static int emoji_1f61b = 2130838114;
			
			// aapt resource value: 0x7f020263
			public static int emoji_1f61c = 2130838115;
			
			// aapt resource value: 0x7f020264
			public static int emoji_1f61d = 2130838116;
			
			// aapt resource value: 0x7f020265
			public static int emoji_1f61e = 2130838117;
			
			// aapt resource value: 0x7f020266
			public static int emoji_1f61f = 2130838118;
			
			// aapt resource value: 0x7f020267
			public static int emoji_1f620 = 2130838119;
			
			// aapt resource value: 0x7f020268
			public static int emoji_1f621 = 2130838120;
			
			// aapt resource value: 0x7f020269
			public static int emoji_1f622 = 2130838121;
			
			// aapt resource value: 0x7f02026a
			public static int emoji_1f623 = 2130838122;
			
			// aapt resource value: 0x7f02026b
			public static int emoji_1f624 = 2130838123;
			
			// aapt resource value: 0x7f02026c
			public static int emoji_1f625 = 2130838124;
			
			// aapt resource value: 0x7f02026d
			public static int emoji_1f626 = 2130838125;
			
			// aapt resource value: 0x7f02026e
			public static int emoji_1f627 = 2130838126;
			
			// aapt resource value: 0x7f02026f
			public static int emoji_1f628 = 2130838127;
			
			// aapt resource value: 0x7f020270
			public static int emoji_1f629 = 2130838128;
			
			// aapt resource value: 0x7f020271
			public static int emoji_1f62a = 2130838129;
			
			// aapt resource value: 0x7f020272
			public static int emoji_1f62b = 2130838130;
			
			// aapt resource value: 0x7f020273
			public static int emoji_1f62c = 2130838131;
			
			// aapt resource value: 0x7f020274
			public static int emoji_1f62d = 2130838132;
			
			// aapt resource value: 0x7f020275
			public static int emoji_1f62e = 2130838133;
			
			// aapt resource value: 0x7f020276
			public static int emoji_1f62f = 2130838134;
			
			// aapt resource value: 0x7f020277
			public static int emoji_1f630 = 2130838135;
			
			// aapt resource value: 0x7f020278
			public static int emoji_1f631 = 2130838136;
			
			// aapt resource value: 0x7f020279
			public static int emoji_1f632 = 2130838137;
			
			// aapt resource value: 0x7f02027a
			public static int emoji_1f633 = 2130838138;
			
			// aapt resource value: 0x7f02027b
			public static int emoji_1f634 = 2130838139;
			
			// aapt resource value: 0x7f02027c
			public static int emoji_1f635 = 2130838140;
			
			// aapt resource value: 0x7f02027d
			public static int emoji_1f636 = 2130838141;
			
			// aapt resource value: 0x7f02027e
			public static int emoji_1f637 = 2130838142;
			
			// aapt resource value: 0x7f02027f
			public static int emoji_1f638 = 2130838143;
			
			// aapt resource value: 0x7f020280
			public static int emoji_1f639 = 2130838144;
			
			// aapt resource value: 0x7f020281
			public static int emoji_1f63a = 2130838145;
			
			// aapt resource value: 0x7f020282
			public static int emoji_1f63b = 2130838146;
			
			// aapt resource value: 0x7f020283
			public static int emoji_1f63c = 2130838147;
			
			// aapt resource value: 0x7f020284
			public static int emoji_1f63d = 2130838148;
			
			// aapt resource value: 0x7f020285
			public static int emoji_1f63e = 2130838149;
			
			// aapt resource value: 0x7f020286
			public static int emoji_1f63f = 2130838150;
			
			// aapt resource value: 0x7f020287
			public static int emoji_1f640 = 2130838151;
			
			// aapt resource value: 0x7f020288
			public static int emoji_1f645 = 2130838152;
			
			// aapt resource value: 0x7f020289
			public static int emoji_1f646 = 2130838153;
			
			// aapt resource value: 0x7f02028a
			public static int emoji_1f647 = 2130838154;
			
			// aapt resource value: 0x7f02028b
			public static int emoji_1f648 = 2130838155;
			
			// aapt resource value: 0x7f02028c
			public static int emoji_1f649 = 2130838156;
			
			// aapt resource value: 0x7f02028d
			public static int emoji_1f64a = 2130838157;
			
			// aapt resource value: 0x7f02028e
			public static int emoji_1f64b = 2130838158;
			
			// aapt resource value: 0x7f02028f
			public static int emoji_1f64c = 2130838159;
			
			// aapt resource value: 0x7f020290
			public static int emoji_1f64d = 2130838160;
			
			// aapt resource value: 0x7f020291
			public static int emoji_1f64e = 2130838161;
			
			// aapt resource value: 0x7f020292
			public static int emoji_1f64f = 2130838162;
			
			// aapt resource value: 0x7f020293
			public static int emoji_1f680 = 2130838163;
			
			// aapt resource value: 0x7f020294
			public static int emoji_1f681 = 2130838164;
			
			// aapt resource value: 0x7f020295
			public static int emoji_1f682 = 2130838165;
			
			// aapt resource value: 0x7f020296
			public static int emoji_1f683 = 2130838166;
			
			// aapt resource value: 0x7f020297
			public static int emoji_1f684 = 2130838167;
			
			// aapt resource value: 0x7f020298
			public static int emoji_1f685 = 2130838168;
			
			// aapt resource value: 0x7f020299
			public static int emoji_1f686 = 2130838169;
			
			// aapt resource value: 0x7f02029a
			public static int emoji_1f687 = 2130838170;
			
			// aapt resource value: 0x7f02029b
			public static int emoji_1f688 = 2130838171;
			
			// aapt resource value: 0x7f02029c
			public static int emoji_1f689 = 2130838172;
			
			// aapt resource value: 0x7f02029d
			public static int emoji_1f68a = 2130838173;
			
			// aapt resource value: 0x7f02029e
			public static int emoji_1f68b = 2130838174;
			
			// aapt resource value: 0x7f02029f
			public static int emoji_1f68c = 2130838175;
			
			// aapt resource value: 0x7f0202a0
			public static int emoji_1f68d = 2130838176;
			
			// aapt resource value: 0x7f0202a1
			public static int emoji_1f68e = 2130838177;
			
			// aapt resource value: 0x7f0202a2
			public static int emoji_1f68f = 2130838178;
			
			// aapt resource value: 0x7f0202a3
			public static int emoji_1f690 = 2130838179;
			
			// aapt resource value: 0x7f0202a4
			public static int emoji_1f691 = 2130838180;
			
			// aapt resource value: 0x7f0202a5
			public static int emoji_1f692 = 2130838181;
			
			// aapt resource value: 0x7f0202a6
			public static int emoji_1f693 = 2130838182;
			
			// aapt resource value: 0x7f0202a7
			public static int emoji_1f694 = 2130838183;
			
			// aapt resource value: 0x7f0202a8
			public static int emoji_1f695 = 2130838184;
			
			// aapt resource value: 0x7f0202a9
			public static int emoji_1f696 = 2130838185;
			
			// aapt resource value: 0x7f0202aa
			public static int emoji_1f697 = 2130838186;
			
			// aapt resource value: 0x7f0202ab
			public static int emoji_1f698 = 2130838187;
			
			// aapt resource value: 0x7f0202ac
			public static int emoji_1f699 = 2130838188;
			
			// aapt resource value: 0x7f0202ad
			public static int emoji_1f69a = 2130838189;
			
			// aapt resource value: 0x7f0202ae
			public static int emoji_1f69b = 2130838190;
			
			// aapt resource value: 0x7f0202af
			public static int emoji_1f69c = 2130838191;
			
			// aapt resource value: 0x7f0202b0
			public static int emoji_1f69d = 2130838192;
			
			// aapt resource value: 0x7f0202b1
			public static int emoji_1f69e = 2130838193;
			
			// aapt resource value: 0x7f0202b2
			public static int emoji_1f69f = 2130838194;
			
			// aapt resource value: 0x7f0202b3
			public static int emoji_1f6a0 = 2130838195;
			
			// aapt resource value: 0x7f0202b4
			public static int emoji_1f6a1 = 2130838196;
			
			// aapt resource value: 0x7f0202b5
			public static int emoji_1f6a2 = 2130838197;
			
			// aapt resource value: 0x7f0202b6
			public static int emoji_1f6a3 = 2130838198;
			
			// aapt resource value: 0x7f0202b7
			public static int emoji_1f6a4 = 2130838199;
			
			// aapt resource value: 0x7f0202b8
			public static int emoji_1f6a5 = 2130838200;
			
			// aapt resource value: 0x7f0202b9
			public static int emoji_1f6a6 = 2130838201;
			
			// aapt resource value: 0x7f0202ba
			public static int emoji_1f6a7 = 2130838202;
			
			// aapt resource value: 0x7f0202bb
			public static int emoji_1f6a8 = 2130838203;
			
			// aapt resource value: 0x7f0202bc
			public static int emoji_1f6a9 = 2130838204;
			
			// aapt resource value: 0x7f0202bd
			public static int emoji_1f6aa = 2130838205;
			
			// aapt resource value: 0x7f0202be
			public static int emoji_1f6ab = 2130838206;
			
			// aapt resource value: 0x7f0202bf
			public static int emoji_1f6ac = 2130838207;
			
			// aapt resource value: 0x7f0202c0
			public static int emoji_1f6ad = 2130838208;
			
			// aapt resource value: 0x7f0202c1
			public static int emoji_1f6ae = 2130838209;
			
			// aapt resource value: 0x7f0202c2
			public static int emoji_1f6af = 2130838210;
			
			// aapt resource value: 0x7f0202c3
			public static int emoji_1f6b0 = 2130838211;
			
			// aapt resource value: 0x7f0202c4
			public static int emoji_1f6b1 = 2130838212;
			
			// aapt resource value: 0x7f0202c5
			public static int emoji_1f6b2 = 2130838213;
			
			// aapt resource value: 0x7f0202c6
			public static int emoji_1f6b3 = 2130838214;
			
			// aapt resource value: 0x7f0202c7
			public static int emoji_1f6b4 = 2130838215;
			
			// aapt resource value: 0x7f0202c8
			public static int emoji_1f6b5 = 2130838216;
			
			// aapt resource value: 0x7f0202c9
			public static int emoji_1f6b6 = 2130838217;
			
			// aapt resource value: 0x7f0202ca
			public static int emoji_1f6b7 = 2130838218;
			
			// aapt resource value: 0x7f0202cb
			public static int emoji_1f6b8 = 2130838219;
			
			// aapt resource value: 0x7f0202cc
			public static int emoji_1f6b9 = 2130838220;
			
			// aapt resource value: 0x7f0202cd
			public static int emoji_1f6ba = 2130838221;
			
			// aapt resource value: 0x7f0202ce
			public static int emoji_1f6bb = 2130838222;
			
			// aapt resource value: 0x7f0202cf
			public static int emoji_1f6bc = 2130838223;
			
			// aapt resource value: 0x7f0202d0
			public static int emoji_1f6bd = 2130838224;
			
			// aapt resource value: 0x7f0202d1
			public static int emoji_1f6be = 2130838225;
			
			// aapt resource value: 0x7f0202d2
			public static int emoji_1f6bf = 2130838226;
			
			// aapt resource value: 0x7f0202d3
			public static int emoji_1f6c0 = 2130838227;
			
			// aapt resource value: 0x7f0202d4
			public static int emoji_1f6c1 = 2130838228;
			
			// aapt resource value: 0x7f0202d5
			public static int emoji_1f6c2 = 2130838229;
			
			// aapt resource value: 0x7f0202d6
			public static int emoji_1f6c3 = 2130838230;
			
			// aapt resource value: 0x7f0202d7
			public static int emoji_1f6c4 = 2130838231;
			
			// aapt resource value: 0x7f0202d8
			public static int emoji_1f6c5 = 2130838232;
			
			// aapt resource value: 0x7f0202d9
			public static int emoji_203c = 2130838233;
			
			// aapt resource value: 0x7f0202da
			public static int emoji_2049 = 2130838234;
			
			// aapt resource value: 0x7f0202db
			public static int emoji_2122 = 2130838235;
			
			// aapt resource value: 0x7f0202dc
			public static int emoji_2139 = 2130838236;
			
			// aapt resource value: 0x7f0202dd
			public static int emoji_2194 = 2130838237;
			
			// aapt resource value: 0x7f0202de
			public static int emoji_2195 = 2130838238;
			
			// aapt resource value: 0x7f0202df
			public static int emoji_2196 = 2130838239;
			
			// aapt resource value: 0x7f0202e0
			public static int emoji_2197 = 2130838240;
			
			// aapt resource value: 0x7f0202e1
			public static int emoji_2198 = 2130838241;
			
			// aapt resource value: 0x7f0202e2
			public static int emoji_2199 = 2130838242;
			
			// aapt resource value: 0x7f0202e3
			public static int emoji_21a9 = 2130838243;
			
			// aapt resource value: 0x7f0202e4
			public static int emoji_21aa = 2130838244;
			
			// aapt resource value: 0x7f0202e5
			public static int emoji_231a = 2130838245;
			
			// aapt resource value: 0x7f0202e6
			public static int emoji_231b = 2130838246;
			
			// aapt resource value: 0x7f0202e7
			public static int emoji_23e9 = 2130838247;
			
			// aapt resource value: 0x7f0202e8
			public static int emoji_23ea = 2130838248;
			
			// aapt resource value: 0x7f0202e9
			public static int emoji_23eb = 2130838249;
			
			// aapt resource value: 0x7f0202ea
			public static int emoji_23ec = 2130838250;
			
			// aapt resource value: 0x7f0202eb
			public static int emoji_23f0 = 2130838251;
			
			// aapt resource value: 0x7f0202ec
			public static int emoji_23f3 = 2130838252;
			
			// aapt resource value: 0x7f0202ed
			public static int emoji_24c2 = 2130838253;
			
			// aapt resource value: 0x7f0202ee
			public static int emoji_25aa = 2130838254;
			
			// aapt resource value: 0x7f0202ef
			public static int emoji_25ab = 2130838255;
			
			// aapt resource value: 0x7f0202f0
			public static int emoji_25b6 = 2130838256;
			
			// aapt resource value: 0x7f0202f1
			public static int emoji_25c0 = 2130838257;
			
			// aapt resource value: 0x7f0202f2
			public static int emoji_25fb = 2130838258;
			
			// aapt resource value: 0x7f0202f3
			public static int emoji_25fc = 2130838259;
			
			// aapt resource value: 0x7f0202f4
			public static int emoji_25fd = 2130838260;
			
			// aapt resource value: 0x7f0202f5
			public static int emoji_25fe = 2130838261;
			
			// aapt resource value: 0x7f0202f6
			public static int emoji_2600 = 2130838262;
			
			// aapt resource value: 0x7f0202f7
			public static int emoji_2601 = 2130838263;
			
			// aapt resource value: 0x7f0202f8
			public static int emoji_260e = 2130838264;
			
			// aapt resource value: 0x7f0202f9
			public static int emoji_2611 = 2130838265;
			
			// aapt resource value: 0x7f0202fa
			public static int emoji_2614 = 2130838266;
			
			// aapt resource value: 0x7f0202fb
			public static int emoji_2615 = 2130838267;
			
			// aapt resource value: 0x7f0202fc
			public static int emoji_261d = 2130838268;
			
			// aapt resource value: 0x7f0202fd
			public static int emoji_263a = 2130838269;
			
			// aapt resource value: 0x7f0202fe
			public static int emoji_2648 = 2130838270;
			
			// aapt resource value: 0x7f0202ff
			public static int emoji_2649 = 2130838271;
			
			// aapt resource value: 0x7f020300
			public static int emoji_264a = 2130838272;
			
			// aapt resource value: 0x7f020301
			public static int emoji_264b = 2130838273;
			
			// aapt resource value: 0x7f020302
			public static int emoji_264c = 2130838274;
			
			// aapt resource value: 0x7f020303
			public static int emoji_264d = 2130838275;
			
			// aapt resource value: 0x7f020304
			public static int emoji_264e = 2130838276;
			
			// aapt resource value: 0x7f020305
			public static int emoji_264f = 2130838277;
			
			// aapt resource value: 0x7f020306
			public static int emoji_2650 = 2130838278;
			
			// aapt resource value: 0x7f020307
			public static int emoji_2651 = 2130838279;
			
			// aapt resource value: 0x7f020308
			public static int emoji_2652 = 2130838280;
			
			// aapt resource value: 0x7f020309
			public static int emoji_2653 = 2130838281;
			
			// aapt resource value: 0x7f02030a
			public static int emoji_2660 = 2130838282;
			
			// aapt resource value: 0x7f02030b
			public static int emoji_2663 = 2130838283;
			
			// aapt resource value: 0x7f02030c
			public static int emoji_2665 = 2130838284;
			
			// aapt resource value: 0x7f02030d
			public static int emoji_2666 = 2130838285;
			
			// aapt resource value: 0x7f02030e
			public static int emoji_2668 = 2130838286;
			
			// aapt resource value: 0x7f02030f
			public static int emoji_267b = 2130838287;
			
			// aapt resource value: 0x7f020310
			public static int emoji_267f = 2130838288;
			
			// aapt resource value: 0x7f020311
			public static int emoji_2693 = 2130838289;
			
			// aapt resource value: 0x7f020312
			public static int emoji_26a0 = 2130838290;
			
			// aapt resource value: 0x7f020313
			public static int emoji_26a1 = 2130838291;
			
			// aapt resource value: 0x7f020314
			public static int emoji_26aa = 2130838292;
			
			// aapt resource value: 0x7f020315
			public static int emoji_26ab = 2130838293;
			
			// aapt resource value: 0x7f020316
			public static int emoji_26bd = 2130838294;
			
			// aapt resource value: 0x7f020317
			public static int emoji_26be = 2130838295;
			
			// aapt resource value: 0x7f020318
			public static int emoji_26c4 = 2130838296;
			
			// aapt resource value: 0x7f020319
			public static int emoji_26c5 = 2130838297;
			
			// aapt resource value: 0x7f02031a
			public static int emoji_26ce = 2130838298;
			
			// aapt resource value: 0x7f02031b
			public static int emoji_26d4 = 2130838299;
			
			// aapt resource value: 0x7f02031c
			public static int emoji_26ea = 2130838300;
			
			// aapt resource value: 0x7f02031d
			public static int emoji_26f2 = 2130838301;
			
			// aapt resource value: 0x7f02031e
			public static int emoji_26f3 = 2130838302;
			
			// aapt resource value: 0x7f02031f
			public static int emoji_26f5 = 2130838303;
			
			// aapt resource value: 0x7f020320
			public static int emoji_26fa = 2130838304;
			
			// aapt resource value: 0x7f020321
			public static int emoji_26fd = 2130838305;
			
			// aapt resource value: 0x7f020322
			public static int emoji_2702 = 2130838306;
			
			// aapt resource value: 0x7f020323
			public static int emoji_2705 = 2130838307;
			
			// aapt resource value: 0x7f020324
			public static int emoji_2708 = 2130838308;
			
			// aapt resource value: 0x7f020325
			public static int emoji_2709 = 2130838309;
			
			// aapt resource value: 0x7f020326
			public static int emoji_270a = 2130838310;
			
			// aapt resource value: 0x7f020327
			public static int emoji_270b = 2130838311;
			
			// aapt resource value: 0x7f020328
			public static int emoji_270c = 2130838312;
			
			// aapt resource value: 0x7f020329
			public static int emoji_270f = 2130838313;
			
			// aapt resource value: 0x7f02032a
			public static int emoji_2712 = 2130838314;
			
			// aapt resource value: 0x7f02032b
			public static int emoji_2714 = 2130838315;
			
			// aapt resource value: 0x7f02032c
			public static int emoji_2716 = 2130838316;
			
			// aapt resource value: 0x7f02032d
			public static int emoji_2728 = 2130838317;
			
			// aapt resource value: 0x7f02032e
			public static int emoji_2733 = 2130838318;
			
			// aapt resource value: 0x7f02032f
			public static int emoji_2734 = 2130838319;
			
			// aapt resource value: 0x7f020330
			public static int emoji_2744 = 2130838320;
			
			// aapt resource value: 0x7f020331
			public static int emoji_2747 = 2130838321;
			
			// aapt resource value: 0x7f020332
			public static int emoji_274c = 2130838322;
			
			// aapt resource value: 0x7f020333
			public static int emoji_274e = 2130838323;
			
			// aapt resource value: 0x7f020334
			public static int emoji_2753 = 2130838324;
			
			// aapt resource value: 0x7f020335
			public static int emoji_2754 = 2130838325;
			
			// aapt resource value: 0x7f020336
			public static int emoji_2755 = 2130838326;
			
			// aapt resource value: 0x7f020337
			public static int emoji_2757 = 2130838327;
			
			// aapt resource value: 0x7f020338
			public static int emoji_2764 = 2130838328;
			
			// aapt resource value: 0x7f020339
			public static int emoji_2795 = 2130838329;
			
			// aapt resource value: 0x7f02033a
			public static int emoji_2796 = 2130838330;
			
			// aapt resource value: 0x7f02033b
			public static int emoji_2797 = 2130838331;
			
			// aapt resource value: 0x7f02033c
			public static int emoji_27a1 = 2130838332;
			
			// aapt resource value: 0x7f02033d
			public static int emoji_27b0 = 2130838333;
			
			// aapt resource value: 0x7f02033e
			public static int emoji_27bf = 2130838334;
			
			// aapt resource value: 0x7f02033f
			public static int emoji_2934 = 2130838335;
			
			// aapt resource value: 0x7f020340
			public static int emoji_2935 = 2130838336;
			
			// aapt resource value: 0x7f020341
			public static int emoji_2b05 = 2130838337;
			
			// aapt resource value: 0x7f020342
			public static int emoji_2b06 = 2130838338;
			
			// aapt resource value: 0x7f020343
			public static int emoji_2b07 = 2130838339;
			
			// aapt resource value: 0x7f020344
			public static int emoji_2b1b = 2130838340;
			
			// aapt resource value: 0x7f020345
			public static int emoji_2b1c = 2130838341;
			
			// aapt resource value: 0x7f020346
			public static int emoji_2b50 = 2130838342;
			
			// aapt resource value: 0x7f020347
			public static int emoji_2b55 = 2130838343;
			
			// aapt resource value: 0x7f020348
			public static int emoji_3030 = 2130838344;
			
			// aapt resource value: 0x7f020349
			public static int emoji_303d = 2130838345;
			
			// aapt resource value: 0x7f02034a
			public static int emoji_3297 = 2130838346;
			
			// aapt resource value: 0x7f02034b
			public static int emoji_3299 = 2130838347;
			
			// aapt resource value: 0x7f02034c
			public static int ic_emoji_nature_light = 2130838348;
			
			// aapt resource value: 0x7f02034d
			public static int ic_emoji_nature_light_activated = 2130838349;
			
			// aapt resource value: 0x7f02034e
			public static int ic_emoji_nature_light_normal = 2130838350;
			
			// aapt resource value: 0x7f02034f
			public static int ic_emoji_objects_light = 2130838351;
			
			// aapt resource value: 0x7f020350
			public static int ic_emoji_objects_light_activated = 2130838352;
			
			// aapt resource value: 0x7f020351
			public static int ic_emoji_objects_light_normal = 2130838353;
			
			// aapt resource value: 0x7f020352
			public static int ic_emoji_people_light = 2130838354;
			
			// aapt resource value: 0x7f020353
			public static int ic_emoji_people_light_activated = 2130838355;
			
			// aapt resource value: 0x7f020354
			public static int ic_emoji_people_light_normal = 2130838356;
			
			// aapt resource value: 0x7f020355
			public static int ic_emoji_places_light = 2130838357;
			
			// aapt resource value: 0x7f020356
			public static int ic_emoji_places_light_activated = 2130838358;
			
			// aapt resource value: 0x7f020357
			public static int ic_emoji_places_light_normal = 2130838359;
			
			// aapt resource value: 0x7f020358
			public static int ic_emoji_recent_light = 2130838360;
			
			// aapt resource value: 0x7f020359
			public static int ic_emoji_recent_light_activated = 2130838361;
			
			// aapt resource value: 0x7f02035a
			public static int ic_emoji_recent_light_normal = 2130838362;
			
			// aapt resource value: 0x7f02035b
			public static int ic_emoji_symbols_light = 2130838363;
			
			// aapt resource value: 0x7f02035c
			public static int ic_emoji_symbols_light_activated = 2130838364;
			
			// aapt resource value: 0x7f02035d
			public static int ic_emoji_symbols_light_normal = 2130838365;
			
			// aapt resource value: 0x7f02035e
			public static int ic_launcher = 2130838366;
			
			// aapt resource value: 0x7f02035f
			public static int keyboard_background_holo = 2130838367;
			
			// aapt resource value: 0x7f020360
			public static int orca_attach_camera_normal = 2130838368;
			
			// aapt resource value: 0x7f020361
			public static int orca_attach_camera_pressed = 2130838369;
			
			// aapt resource value: 0x7f020362
			public static int orca_attach_location_normal = 2130838370;
			
			// aapt resource value: 0x7f020363
			public static int orca_attach_location_pressed = 2130838371;
			
			// aapt resource value: 0x7f020364
			public static int orca_attach_photo_normal = 2130838372;
			
			// aapt resource value: 0x7f020365
			public static int orca_attach_photo_pressed = 2130838373;
			
			// aapt resource value: 0x7f020366
			public static int orca_attachments_arrow = 2130838374;
			
			// aapt resource value: 0x7f020367
			public static int orca_attachments_arrow_reversed = 2130838375;
			
			// aapt resource value: 0x7f020368
			public static int orca_composer_divider_horizontal = 2130838376;
			
			// aapt resource value: 0x7f020369
			public static int orca_composer_divider_vertical = 2130838377;
			
			// aapt resource value: 0x7f02036a
			public static int orca_composer_popup_active_normal = 2130838378;
			
			// aapt resource value: 0x7f02036b
			public static int orca_composer_popup_active_pressed = 2130838379;
			
			// aapt resource value: 0x7f02036c
			public static int orca_composer_popup_normal = 2130838380;
			
			// aapt resource value: 0x7f02036d
			public static int orca_composer_popup_pressed = 2130838381;
			
			// aapt resource value: 0x7f02036e
			public static int orca_composer_tab = 2130838382;
			
			// aapt resource value: 0x7f02036f
			public static int orca_composer_tab_active = 2130838383;
			
			// aapt resource value: 0x7f020370
			public static int orca_composer_tab_dark = 2130838384;
			
			// aapt resource value: 0x7f020371
			public static int orca_composer_tab_pressed = 2130838385;
			
			// aapt resource value: 0x7f020372
			public static int orca_composer_top_divider = 2130838386;
			
			// aapt resource value: 0x7f020373
			public static int orca_emoji_backspace_back_normal = 2130838387;
			
			// aapt resource value: 0x7f020374
			public static int orca_emoji_backspace_front_normal = 2130838388;
			
			// aapt resource value: 0x7f020375
			public static int orca_emoji_backspace_front_pressed = 2130838389;
			
			// aapt resource value: 0x7f020376
			public static int orca_emoji_category_cars = 2130838390;
			
			// aapt resource value: 0x7f020377
			public static int orca_emoji_category_nature = 2130838391;
			
			// aapt resource value: 0x7f020378
			public static int orca_emoji_category_objects = 2130838392;
			
			// aapt resource value: 0x7f020379
			public static int orca_emoji_category_people = 2130838393;
			
			// aapt resource value: 0x7f02037a
			public static int orca_emoji_category_punctuation = 2130838394;
			
			// aapt resource value: 0x7f02037b
			public static int orca_emoji_more_back_normal = 2130838395;
			
			// aapt resource value: 0x7f02037c
			public static int orca_emoji_more_front_normal = 2130838396;
			
			// aapt resource value: 0x7f02037d
			public static int orca_emoji_more_front_pressed = 2130838397;
			
			// aapt resource value: 0x7f02037e
			public static int sym_keyboard_delete_holo_dark = 2130838398;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int Emoji_GridView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int emojicon_icon = 2131099649;
			
			// aapt resource value: 0x7f060009
			public static int emojis_backspace = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int emojis_pager = 2131099658;
			
			// aapt resource value: 0x7f060002
			public static int emojis_tab = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int emojis_tab_0_recents = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int emojis_tab_1_people = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int emojis_tab_2_nature = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int emojis_tab_3_objects = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int emojis_tab_4_cars = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int emojis_tab_5_punctuation = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int emojicon_grid = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int emojicon_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int emojicons = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Emojicon = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public static int Emojicon_emojiconSize = 0;
			
			// aapt resource value: 2
			public static int Emojicon_emojiconTextLength = 2;
			
			// aapt resource value: 1
			public static int Emojicon_emojiconTextStart = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
